version: "3.8"

services:
    nginx-proxy:
        image: budry/jwilder-nginx-proxy-arm
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./htpasswd:/etc/nginx/htpasswd:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - certs:/etc/nginx/certs:ro
            - confd:/etc/nginx/conf.d
            - vhostd:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

    letsencrypt:
        image: duch/letsencrypt-nginx-proxy-companion:stable
        restart: always
        environment:
            - NGINX_PROXY_CONTAINER=nginx-proxy
        volumes:
            - certs:/etc/nginx/certs:rw
            - confd:/etc/nginx/conf.d
            - vhostd:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro

    netdata:
        image: netdata/netdata:v1.24.0
        restart: always
        expose:
                - "19999"
        volumes:
            - /etc/group:/host/etc/group:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - netdata-etc:/etc/netdata
        cap_add:
            - SYS_PTRACE
        security_opt:
            - apparmor=unconfined
        environment:
            - PGID=995
            - VIRTUAL_HOST=XXXXXXX
            - VIRTUAL_PORT=19999
            - LETSENCRYPT_HOST=XXXXXXX
            - LETSENCRYPT_EMAIL=XXXXXX

volumes:
  certs:
  html:
  vhostd:
  confd:
  netdata-etc:
