version: "3.3"

services:
    netdata:
        image: netdata/netdata:v1.24.0
        restart: always
        ports:
            - 19999:19999
        volumes:
            - /etc/passwd:/host/etc/passwd:ro
            - /etc/group:/host/etc/group:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - netdata-etc:/etc/netdata
        cap_add:
            - SYS_PTRACE
        security_opt:
            - apparmor=unconfined
        environment:
            - PGID=995
volumes:
    netdata-etc:
